version: "3.4"

services:
    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        env_file:
            - .env
        volumes:
            - ./backend:/app
            - /app/node_modules
        command: ["node", "app.js"]
        restart: always
